# Generated by Django 2.0 on 2020-04-29 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reg_Model',
            fields=[
                ('t_id', models.IntegerField(default='')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('email_id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Email ID')),
                ('password', models.CharField(max_length=10)),
                ('mobile_no', models.IntegerField(default=10, null=True)),
                ('address', models.CharField(default='', max_length=100, null=True, verbose_name='Address')),
                ('confirm_password', models.CharField(max_length=10)),
            ],
        ),
    ]
